import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";

import localFont from 'next/font/local'

import { Montserrat } from 'next/font/google';

export const montserrat = Montserrat({
  
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  variable:'--font-montserrat',
  // display:'swap',
  // fallback: ['Arial', 'sans-serif'],
});




 const colusFont = localFont({
  src: [
    {
      path: '../../public/fonts/Colus-Regular.woff',
      weight: '50'
    },
    {
      path: '../../public/fonts/Colus-Regular.woff',
      weight: '100'
    },

    {
      path: '../../public/fonts/Colus-Regular.woff',
      weight: '200'
    },
    {
      path: '../../public/fonts/Colus-Regular.woff',
      weight: '300'
    },
    {
      path: '../../public/fonts/Colus-Regular.woff',
      weight: '400'
    },
  ],
  variable: '--font-colus',
})



// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    // <html lang="en" className={`${colusFont.variable} font-colus`}>
     <html lang="en" className={`${colusFont.variable} ${montserrat.variable}`}>

      <body 
      
      // className={inter.className} 
      // suppressHydrationWarning={true}
      >
        <Providers>
          {children}
        </Providers>  
      </body>
    </html>
  );
}
